# Generated by Django 5.2.12 on 2026-04-07 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('companies', '0002_zone_depot_zone_unique_zone_name_per_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='companies.company', verbose_name='Entreprise'),
        ),
    ]
