# Generated by Django 5.2.12 on 2026-04-14 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_company'),
        ('companies', '0002_zone_depot_zone_unique_zone_name_per_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='companies.depot', verbose_name='Dépôt'),
        ),
    ]
