# Generated by Django 5.2.13 on 2026-04-17 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_depot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression')], max_length=10, verbose_name='Action')),
                ('model_name', models.CharField(help_text='Nom de la classe du modèle (ex: CustomUser, Zone, Depot)', max_length=100, verbose_name='Modèle concerné')),
                ('object_id', models.PositiveIntegerField(verbose_name="ID de l'objet")),
                ('data_before', models.JSONField(blank=True, null=True, verbose_name='Données avant modification')),
                ('data_after', models.JSONField(blank=True, null=True, verbose_name='Données après modification')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='accounts_au_model_n_76c60d_idx'), models.Index(fields=['user', '-timestamp'], name='accounts_au_user_id_1110c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent (navigateur)')),
                ('success', models.BooleanField(verbose_name='Connexion réussie')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('user', models.ForeignKey(blank=True, help_text="Null si l'email n'existe pas dans la base", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Journal de connexion',
                'verbose_name_plural': 'Journaux de connexion',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='accounts_lo_user_id_42ec06_idx'), models.Index(fields=['ip_address', '-timestamp'], name='accounts_lo_ip_addr_1144d8_idx')],
            },
        ),
    ]
