# Generated by Django 5.2.13 on 2026-04-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auditlog_loginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_login_done',
            field=models.BooleanField(default=True, help_text="False pour les Admins créés par le SuperAdmin, jusqu'à ce qu'ils définissent leur mot de passe via le lien email.", verbose_name='Première connexion effectuée'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_login_token',
            field=models.UUIDField(blank=True, help_text='UUID généré à la création par le SuperAdmin. Usage unique — mis à None après utilisation.', null=True, unique=True, verbose_name='Token de première connexion'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tentatives échouées'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom'),
        ),
    ]
