# Generated by Django 5.2.15 on 2026-06-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_login_done',
            field=models.BooleanField(default=False, help_text="False pour les utilisateurs créés par l'Admin ou le SuperAdmin, jusqu'à ce qu'ils définissent leur mot de passe via le lien email.", verbose_name='Première connexion effectuée'),
        ),
    ]
