# Generated by Django 5.2.12 on 2026-04-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_zone_depot_zone_unique_zone_name_per_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude du point central de la zone (ex: 9.537500)', max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='zone',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude du point central de la zone (ex: -13.677300)', max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
