# Generated by Django 5.2.14 on 2026-06-07 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_zone_latitude_zone_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='gestionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depots_geres', to=settings.AUTH_USER_MODEL, verbose_name='Gestionnaire du dépôt'),
        ),
    ]
