# Generated by Django 5.2.14 on 2026-06-06 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_zone_latitude_zone_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('couleur', models.CharField(default='#6366f1', help_text='Code hexadécimal ex: #6366f1', max_length=7, verbose_name='Couleur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='companies.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='Code')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('solde_dette', models.DecimalField(decimal_places=2, default=0, help_text='Montant total dû au fournisseur en GNF', max_digits=14, verbose_name='Solde dette (GNF)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs', to='companies.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['company', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Kilogramme, Litre, Carton', max_length=100, verbose_name='Nom')),
                ('symbole', models.CharField(help_text='Ex: kg, L, ctn', max_length=20, verbose_name='Symbole')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unites', to='companies.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Unité de mesure',
                'verbose_name_plural': 'Unités de mesure',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=60, verbose_name='Référence')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/images/', verbose_name='Image')),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="Prix d'achat (GNF)")),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Prix de vente (GNF)')),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=0, help_text="Déclenchement d'une alerte si stock < seuil", max_digits=10, verbose_name="Seuil d'alerte")),
                ('seuil_max', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock maximum recommandé')),
                ('est_perimable', models.BooleanField(default=False, help_text="Si True, la gestion FEFO s'applique (First Expired First Out)", verbose_name='Périssable / FEFO')),
                ('tva_taux', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux TVA (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='produits.categorie', verbose_name='Catégorie')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='companies.company', verbose_name='Entreprise')),
                ('fournisseur_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_fournis', to='produits.fournisseur', verbose_name='Fournisseur principal')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='produits.unite', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['company', 'nom'],
            },
        ),
        migrations.AddConstraint(
            model_name='categorie',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_categorie_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='fournisseur',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_fournisseur_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='unite',
            constraint=models.UniqueConstraint(fields=('company', 'symbole'), name='unique_unite_symbole_per_company'),
        ),
        migrations.AddConstraint(
            model_name='produit',
            constraint=models.UniqueConstraint(fields=('company', 'reference'), name='unique_produit_reference_per_company'),
        ),
    ]
