# Generated by Django 5.2.14 on 2026-06-07 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_gestionnaire_depot'),
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='tva_taux',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Taux TVA appliqué par défaut aux produits de cette catégorie', max_digits=5, verbose_name='Taux TVA par défaut (%)'),
        ),
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Numéro')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('partiellement_recue', 'Partiellement reçue'), ('recue', 'Reçue'), ('annulee', 'Annulée')], default='brouillon', max_length=30, verbose_name='Statut')),
                ('date_livraison_prevue', models.DateField(blank=True, null=True, verbose_name='Date livraison prévue')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_fournisseurs', to='companies.company', verbose_name='Entreprise')),
                ('created_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_fournisseur_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('depot_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_fournisseurs', to='companies.depot', verbose_name='Dépôt de réception')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='produits.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Commande fournisseur',
                'verbose_name_plural': 'Commandes fournisseurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_qualite', models.PositiveSmallIntegerField(choices=[(1, '1 — Très mauvais'), (2, '2 — Mauvais'), (3, '3 — Moyen'), (4, '4 — Bon'), (5, '5 — Excellent')], verbose_name='Note qualité produits')),
                ('note_delai', models.PositiveSmallIntegerField(choices=[(1, '1 — Très mauvais'), (2, '2 — Mauvais'), (3, '3 — Moyen'), (4, '4 — Bon'), (5, '5 — Excellent')], verbose_name='Note respect des délais')),
                ('note_service', models.PositiveSmallIntegerField(choices=[(1, '1 — Très mauvais'), (2, '2 — Mauvais'), (3, '3 — Moyen'), (4, '4 — Bon'), (5, '5 — Excellent')], verbose_name='Note service client')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commande', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation', to='produits.commandefournisseur', verbose_name='Commande liée')),
                ('evalue_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations_fournisseur', to=settings.AUTH_USER_MODEL, verbose_name='Évalué par')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='produits.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Évaluation fournisseur',
                'verbose_name_plural': 'Évaluations fournisseurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MouvementDetteFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('dette_ajoutee', 'Dette ajoutée'), ('paiement_effectue', 'Paiement effectué'), ('avance', 'Avance')], max_length=20, verbose_name='Type')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant (GNF)')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_dette_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_dette', to='produits.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Mouvement dette fournisseur',
                'verbose_name_plural': 'Mouvements dette fournisseur',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commandee', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité commandée')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Prix unitaire (GNF)')),
                ('quantite_recue', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Quantité reçue')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='produits.commandefournisseur', verbose_name='Commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande_fournisseur', to='produits.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne commande fournisseur',
                'verbose_name_plural': 'Lignes commande fournisseur',
                'constraints': [models.UniqueConstraint(fields=('commande', 'produit'), name='unique_ligne_commande_fournisseur_produit')],
            },
        ),
    ]
