# Generated by Django 5.2.15 on 2026-06-18 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_zone_code_unique_per_company_depot_code_unique_per_zone'),
        ('produits', '0002_categorie_tva_taux_commandefournisseur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandefournisseur',
            name='numero',
            field=models.CharField(max_length=30, verbose_name='Numéro'),
        ),
        migrations.AddConstraint(
            model_name='commandefournisseur',
            constraint=models.UniqueConstraint(fields=('company', 'numero'), name='unique_commande_fournisseur_numero_per_company'),
        ),
    ]
