# Generated by Django 5.2.14 on 2026-06-06 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_zone_latitude_zone_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaissePhysique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Solde actuel (GNF)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caisses', to='companies.company', verbose_name='Entreprise')),
                ('depot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='caisse', to='companies.depot', verbose_name='Dépôt')),
            ],
            options={
                'verbose_name': 'Caisse physique',
                'verbose_name_plural': 'Caisses physiques',
            },
        ),
        migrations.CreateModel(
            name='CompteMobileMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money')], max_length=20, verbose_name='Opérateur')),
                ('numero', models.CharField(max_length=20, verbose_name='Numéro')),
                ('nom_titulaire', models.CharField(max_length=150, verbose_name='Nom titulaire')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Solde (GNF)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_mobile_money', to='companies.company', verbose_name='Entreprise')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comptes_mobile_money', to='companies.depot', verbose_name='Dépôt')),
            ],
            options={
                'verbose_name': 'Compte Mobile Money',
                'verbose_name_plural': 'Comptes Mobile Money',
            },
        ),
        migrations.CreateModel(
            name='SessionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('fermee', 'Fermée')], default='ouverte', max_length=10, verbose_name='Statut')),
                ('solde_ouverture', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Solde ouverture (GNF)')),
                ('solde_fermeture_theorique', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Solde théorique fermeture')),
                ('solde_fermeture_reel', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Solde réel fermeture')),
                ('ecart', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Écart')),
                ('motif_ecart', models.TextField(blank=True, help_text='Obligatoire si écart != 0', verbose_name='Motif écart')),
                ('ouvert_le', models.DateTimeField(auto_now_add=True, verbose_name='Ouvert le')),
                ('ferme_le', models.DateTimeField(blank=True, null=True, verbose_name='Fermé le')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='finance.caissephysique', verbose_name='Caisse')),
                ('caissier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_caisse', to=settings.AUTH_USER_MODEL, verbose_name='Caissier')),
            ],
            options={
                'verbose_name': 'Session caisse',
                'verbose_name_plural': 'Sessions caisse',
                'ordering': ['-ouvert_le'],
            },
        ),
        migrations.CreateModel(
            name='TauxChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devise_source', models.CharField(default='USD', max_length=10, verbose_name='Devise source')),
                ('devise_cible', models.CharField(default='GNF', max_length=10, verbose_name='Devise cible')),
                ('taux', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Taux')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taux_change', to='companies.company', verbose_name='Entreprise')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taux_saisis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Taux de change',
                'verbose_name_plural': 'Taux de change',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('vente', 'Vente'), ('remboursement', 'Remboursement'), ('approvisionnement', 'Approvisionnement caisse'), ('retrait', 'Retrait')], max_length=20, verbose_name='Type')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant (GNF)')),
                ('reference_doc', models.CharField(blank=True, help_text='Numéro de commande ou autre', max_length=50, verbose_name='Référence document')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_caisse', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.sessioncaisse', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Transaction caisse',
                'verbose_name_plural': 'Transactions caisse',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionMobileMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait'), ('paiement_recu', 'Paiement reçu'), ('paiement_envoye', 'Paiement envoyé')], max_length=20, verbose_name='Type')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant (GNF)')),
                ('reference_operateur', models.CharField(blank=True, max_length=100, verbose_name='Référence opérateur')),
                ('reference_doc', models.CharField(blank=True, max_length=50, verbose_name='Référence document interne')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.comptemobilemoney', verbose_name='Compte')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_mobile_money', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Mobile Money',
                'verbose_name_plural': 'Transactions Mobile Money',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='comptemobilemoney',
            constraint=models.UniqueConstraint(fields=('company', 'operateur', 'numero'), name='unique_compte_mobile_money'),
        ),
    ]
