# Generated by Django 5.2.14 on 2026-06-07 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_gestionnaire_depot'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caissephysique',
            name='devise',
            field=models.CharField(default='GNF', max_length=10, verbose_name='Devise'),
        ),
        migrations.CreateModel(
            name='CaisseEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('devise', models.CharField(default='GNF', max_length=10, verbose_name='Devise')),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Solde actuel (GNF)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='caisse_entreprise', to='companies.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Caisse entreprise',
                'verbose_name_plural': 'Caisses entreprise',
            },
        ),
        migrations.CreateModel(
            name='CaisseZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('devise', models.CharField(default='GNF', max_length=10, verbose_name='Devise')),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Solde actuel (GNF)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caisses_zone', to='companies.company', verbose_name='Entreprise')),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='caisse', to='companies.zone', verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'Caisse zone',
                'verbose_name_plural': 'Caisses zone',
            },
        ),
        migrations.CreateModel(
            name='DepenseOperationnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('carburant', 'Carburant'), ('maintenance', 'Maintenance'), ('salaires', 'Salaires'), ('loyer', 'Loyer'), ('fournitures', 'Fournitures'), ('transport', 'Transport'), ('autre', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant (GNF)')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_depense', models.DateField(verbose_name='Date de la dépense')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='finance/depenses/%Y/%m/', verbose_name='Justificatif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses_operationnelles', to='companies.company', verbose_name='Entreprise')),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses_operationnelles', to='companies.depot', verbose_name='Dépôt')),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('session_caisse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='finance.sessioncaisse', verbose_name='Session caisse liée')),
            ],
            options={
                'verbose_name': 'Dépense opérationnelle',
                'verbose_name_plural': 'Dépenses opérationnelles',
                'ordering': ['-date_depense'],
            },
        ),
        migrations.CreateModel(
            name='VersementCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_versement', models.CharField(choices=[('depot_vers_zone', 'Dépôt → Zone'), ('zone_vers_entreprise', 'Zone → Entreprise')], max_length=30, verbose_name='Type versement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Montant')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='finance/versements/%Y/%m/', verbose_name='Justificatif')),
                ('montant_comptage_receveur', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Montant comptage receveur (double comptage)')),
                ('motif_ecart', models.TextField(blank=True, verbose_name='Motif écart')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caisse_dest_entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versements_dest', to='finance.caisseentreprise', verbose_name='Caisse destination (entreprise)')),
                ('caisse_dest_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versements_dest', to='finance.caissezone', verbose_name='Caisse destination (zone)')),
                ('caisse_source_depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versements_source', to='finance.caissephysique', verbose_name='Caisse source (dépôt)')),
                ('caisse_source_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versements_source', to='finance.caissezone', verbose_name='Caisse source (zone)')),
                ('effectue_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versements_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('recu_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versements_recus', to=settings.AUTH_USER_MODEL, verbose_name='Reçu par')),
            ],
            options={
                'verbose_name': 'Versement caisse',
                'verbose_name_plural': 'Versements caisse',
                'ordering': ['-created_at'],
            },
        ),
    ]
