# Generated by Django 5.2.15 on 2026-06-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_sessioncaisse_fermee_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='depenseoperationnelle',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Supprimée le'),
        ),
        migrations.AddField(
            model_name='depenseoperationnelle',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text="Soft-delete — traçabilité §9 : la dépense n'est jamais physiquement supprimée.", verbose_name='Supprimée'),
        ),
    ]
