# Generated by Django 5.2.14 on 2026-06-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LigneMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('quantite_recue', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Quantité reçue')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
            ],
            options={
                'verbose_name': 'Ligne de mission',
                'verbose_name_plural': 'Lignes de mission',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Numéro')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('chargement', 'En chargement'), ('en_transit', 'En transit'), ('arrivee', 'Arrivée à destination'), ('litige', 'Litige'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20, verbose_name='Statut')),
                ('date_depart_prevue', models.DateTimeField(blank=True, null=True, verbose_name='Départ prévu')),
                ('date_depart_reelle', models.DateTimeField(blank=True, null=True, verbose_name='Départ réel')),
                ('date_arrivee_reelle', models.DateTimeField(blank=True, null=True, verbose_name='Arrivée réelle')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('signature_arrivee', models.TextField(blank=True, help_text='Canvas HTML5 encodé en base64', verbose_name='Signature arrivée (base64)')),
                ('motif_litige', models.TextField(blank=True, verbose_name='Motif litige')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PositionGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude')),
                ('vitesse_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Vitesse (km/h)')),
                ('enregistre_le', models.DateTimeField(auto_now_add=True, verbose_name='Enregistré le')),
            ],
            options={
                'verbose_name': 'Position GPS',
                'verbose_name_plural': 'Positions GPS',
                'ordering': ['-enregistre_le'],
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=30, verbose_name='Immatriculation')),
                ('type_vehicule', models.CharField(choices=[('camion', 'Camion'), ('camionnette', 'Camionnette'), ('moto', 'Moto'), ('voiture', 'Voiture')], max_length=20, verbose_name='Type')),
                ('marque', models.CharField(blank=True, max_length=100, verbose_name='Marque')),
                ('modele', models.CharField(blank=True, max_length=100, verbose_name='Modèle')),
                ('capacite_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capacité (kg)')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('en_mission', 'En mission'), ('maintenance', 'En maintenance'), ('hors_service', 'Hors service')], default='disponible', max_length=20, verbose_name='Statut')),
                ('has_nfc', models.BooleanField(default=False, verbose_name='Puce NFC')),
                ('nfc_tag', models.CharField(blank=True, max_length=100, verbose_name='Tag NFC')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
            },
        ),
    ]
