# Generated by Django 5.2.14 on 2026-06-06 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_zone_latitude_zone_longitude'),
        ('logistique', '0001_initial'),
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lignemission',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_mission', to='produits.produit'),
        ),
        migrations.AddField(
            model_name='mission',
            name='chauffeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions_conduites', to=settings.AUTH_USER_MODEL, verbose_name='Chauffeur'),
        ),
        migrations.AddField(
            model_name='mission',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='companies.company', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='mission',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mission',
            name='depot_arrivee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions_arrivee', to='companies.depot', verbose_name='Dépôt arrivée'),
        ),
        migrations.AddField(
            model_name='mission',
            name='depot_depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions_depart', to='companies.depot', verbose_name='Dépôt départ'),
        ),
    ]
