# Generated by Django 5.2.14 on 2026-06-06 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_zone_latitude_zone_longitude'),
        ('logistique', '0002_initial'),
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='transfert_stock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission', to='stocks.transfertstock', verbose_name='Transfert de stock associé'),
        ),
        migrations.AddField(
            model_name='lignemission',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='logistique.mission', verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='positiongps',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='logistique.mission', verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='chauffeur_attitré',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules_assignes', to=settings.AUTH_USER_MODEL, verbose_name='Chauffeur attitré'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='companies.company', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='mission',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='logistique.vehicule', verbose_name='Véhicule'),
        ),
        migrations.AddConstraint(
            model_name='vehicule',
            constraint=models.UniqueConstraint(fields=('company', 'immatriculation'), name='unique_immatriculation_par_company'),
        ),
    ]
