# Generated by Django 5.2.14 on 2026-06-07 02:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='qr_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='QR Code'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='annee',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année de fabrication'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='kilometrage_actuel',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilométrage actuel (km)'),
        ),
        migrations.CreateModel(
            name='ConsommationCarburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_carburant', models.CharField(choices=[('essence', 'Essence'), ('gasoil', 'Gasoil'), ('gpl', 'GPL')], default='gasoil', max_length=20, verbose_name='Type de carburant')),
                ('quantite_litres', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantité (litres)')),
                ('prix_par_litre', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par litre (GNF)')),
                ('kilometrage', models.PositiveIntegerField(verbose_name='Kilométrage au plein')),
                ('date_plein', models.DateField(verbose_name='Date du plein')),
                ('station', models.CharField(blank=True, max_length=150, verbose_name='Station')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pleins_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consommations_carburant', to='logistique.mission', verbose_name='Mission')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations_carburant', to='logistique.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Consommation carburant',
                'verbose_name_plural': 'Consommations carburant',
                'ordering': ['-date_plein'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('assurance', 'Assurance'), ('visite_technique', 'Visite technique'), ('carte_grise', 'Carte grise'), ('autre', 'Autre')], max_length=30, verbose_name='Type')),
                ('fichier', models.FileField(upload_to='vehicules/documents/', verbose_name='Fichier')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='logistique.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Document véhicule',
                'verbose_name_plural': 'Documents véhicule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_maintenance', models.CharField(choices=[('preventive', 'Préventive'), ('corrective', 'Corrective')], max_length=20, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('kilometrage_au_moment', models.PositiveIntegerField(default=0, verbose_name='Kilométrage au moment')),
                ('cout', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Coût (GNF)')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée')], default='planifiee', max_length=20, verbose_name='Statut')),
                ('date_planifiee', models.DateField(verbose_name='Date planifiée')),
                ('date_reelle', models.DateField(blank=True, null=True, verbose_name='Date réelle')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='logistique.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'ordering': ['-date_planifiee'],
            },
        ),
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_declaration', models.DateTimeField(auto_now_add=True, verbose_name='Date de déclaration')),
                ('cout_reparation', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Coût réparation (GNF)')),
                ('statut', models.CharField(choices=[('declaree', 'Déclarée'), ('en_reparation', 'En réparation'), ('resolue', 'Résolue')], default='declaree', max_length=20, verbose_name='Statut')),
                ('resolu_le', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
                ('declare_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pannes_declarees', to=settings.AUTH_USER_MODEL, verbose_name='Déclaré par')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pannes', to='logistique.mission', verbose_name='Mission en cours')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pannes', to='logistique.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Panne',
                'verbose_name_plural': 'Pannes',
                'ordering': ['-date_declaration'],
            },
        ),
    ]
