# Generated by Django 5.2.14 on 2026-06-06 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_zone_latitude_zone_longitude'),
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='Code')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('points_fidelite', models.PositiveIntegerField(default=0, verbose_name='Points fidélité')),
                ('solde_credit', models.DecimalField(decimal_places=2, default=0, help_text='Montant dû par le client (créances)', max_digits=14, verbose_name='Solde crédit (GNF)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='companies.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['company', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Numéro')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('confirmee', 'Confirmée'), ('en_preparation', 'En préparation'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('mode_paiement', models.CharField(choices=[('comptant', 'Comptant'), ('partiel', 'Partiel'), ('credit', 'Crédit')], default='comptant', max_length=20, verbose_name='Mode paiement')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant HT')),
                ('tva_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total TVA')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant TTC')),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Remise (GNF)')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant payé')),
                ('points_utilises', models.PositiveIntegerField(default=0, verbose_name='Points fidélité utilisés')),
                ('points_gagnes', models.PositiveIntegerField(default=0, verbose_name='Points fidélité gagnés')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caissier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_saisies', to=settings.AUTH_USER_MODEL, verbose_name='Caissier')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='ventes.client', verbose_name='Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='companies.company', verbose_name='Entreprise')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='companies.depot', verbose_name='Dépôt')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire HT')),
                ('tva_taux', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux TVA (%)')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant HT')),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant TVA')),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant TTC')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.commande', verbose_name='Commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='produits.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money'), ('virement', 'Virement bancaire'), ('points_fidelite', 'Points fidélité')], max_length=20, verbose_name='Mode')),
                ('reference', models.CharField(blank=True, help_text='Numéro de transaction mobile money / virement', max_length=100, verbose_name='Référence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caissier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_saisis', to=settings.AUTH_USER_MODEL, verbose_name='Caissier')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='ventes.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParametresFidelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activé')),
                ('tranche_montant', models.DecimalField(decimal_places=2, default=10000, help_text='Pour chaque tranche achetée, le client gagne des points', max_digits=12, verbose_name='Tranche montant (GNF)')),
                ('points_par_tranche', models.PositiveIntegerField(default=1, verbose_name='Points par tranche')),
                ('valeur_point_gnf', models.DecimalField(decimal_places=2, default=100, help_text='1 point = x GNF de réduction', max_digits=10, verbose_name="Valeur d'un point (GNF)")),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametres_fidelite', to='companies.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Paramètres fidélité',
                'verbose_name_plural': 'Paramètres fidélité',
            },
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_client_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='lignecommande',
            constraint=models.UniqueConstraint(fields=('commande', 'produit'), name='unique_ligne_commande_produit'),
        ),
    ]
