# Generated by Django 5.2.14 on 2026-06-07 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_gestionnaire_depot'),
        ('produits', '0002_categorie_tva_taux_commandefournisseur_and_more'),
        ('ventes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Numéro')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('expire', 'Expiré'), ('converti', 'Converti en commande')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to='ventes.client', verbose_name='Client')),
                ('commande', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_source', to='ventes.commande', verbose_name='Commande générée')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='companies.company', verbose_name='Entreprise')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis', to='companies.depot', verbose_name='Dépôt')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoriquePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('gain', 'Gain'), ('utilisation', 'Utilisation'), ('annulation', 'Annulation')], max_length=20, verbose_name='Type')),
                ('points', models.IntegerField(verbose_name='Points (+ gain / - utilisation)')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_points', to='ventes.client', verbose_name='Client')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_points', to='ventes.commande', verbose_name='Commande liée')),
            ],
            options={
                'verbose_name': 'Historique points fidélité',
                'verbose_name_plural': 'Historiques points fidélité',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('type_promotion', models.CharField(choices=[('pourcentage', 'Pourcentage (%)'), ('montant_fixe', 'Montant fixe (GNF)'), ('prix_special', 'Prix spécial')], max_length=20, verbose_name='Type')),
                ('valeur', models.DecimalField(decimal_places=2, help_text='% ou montant fixe ou prix spécial selon le type', max_digits=12, verbose_name='Valeur')),
                ('cible', models.CharField(choices=[('tous', 'Tous les clients'), ('client', 'Client spécifique'), ('categorie', 'Catégorie de produit')], default='tous', max_length=20, verbose_name='Cible')),
                ('date_debut', models.DateField(verbose_name='Date début')),
                ('date_fin', models.DateField(verbose_name='Date fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='produits.categorie', verbose_name='Catégorie cible')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='ventes.client', verbose_name='Client cible')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='companies.company', verbose_name='Entreprise')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='produits.produit', verbose_name='Produit cible')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='RetourCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('defectueux', 'Produit défectueux'), ('erreur_livraison', 'Erreur de livraison'), ('insatisfaction', 'Insatisfaction client'), ('autre', 'Autre')], max_length=30, verbose_name='Motif')),
                ('type_retour', models.CharField(choices=[('remboursement', 'Remboursement espèces'), ('avoir', 'Avoir client'), ('echange', 'Échange produit')], max_length=20, verbose_name='Type de retour')),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant remboursé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours', to='ventes.commande', verbose_name='Commande')),
                ('traite_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours_traites', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': 'Retour commande',
                'verbose_name_plural': 'Retours commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire HT')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.devis', verbose_name='Devis')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_devis', to='produits.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'verbose_name_plural': 'Lignes de devis',
                'constraints': [models.UniqueConstraint(fields=('devis', 'produit'), name='unique_ligne_devis_produit')],
            },
        ),
        migrations.CreateModel(
            name='LigneRetour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('motif_ligne', models.TextField(blank=True, verbose_name='Motif ligne')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_retour', to='produits.produit', verbose_name='Produit')),
                ('retour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.retourcommande', verbose_name='Retour')),
            ],
            options={
                'verbose_name': 'Ligne de retour',
                'verbose_name_plural': 'Lignes de retour',
                'constraints': [models.UniqueConstraint(fields=('retour', 'produit'), name='unique_ligne_retour_produit')],
            },
        ),
    ]
