# Generated by Django 5.2.14 on 2026-06-06 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_zone_latitude_zone_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=30, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('poste', models.CharField(blank=True, max_length=150, verbose_name='Poste')),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('salaire_base', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Salaire de base (GNF)')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('conge', 'En congé'), ('suspendu', 'Suspendu'), ('quitte', 'A quitté')], default='actif', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='companies.company', verbose_name='Entreprise')),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='companies.depot')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_employe', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['company', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('contrat', 'Contrat de travail'), ('facture_fournisseur', 'Facture fournisseur'), ('bon_livraison', 'Bon de livraison'), ('autre', 'Autre')], max_length=30, verbose_name='Type')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Fichier')),
                ('reference_externe', models.CharField(blank=True, max_length=100, verbose_name='Référence externe')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.company', verbose_name='Entreprise')),
                ('uploade_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploades', to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('annuel', 'Congé annuel'), ('maladie', 'Congé maladie'), ('maternite', 'Congé maternité'), ('sans_solde', 'Sans solde'), ('autre', 'Autre')], max_length=20, verbose_name='Type')),
                ('date_debut', models.DateField(verbose_name='Date début')),
                ('date_fin', models.DateField(verbose_name='Date fin')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('motif', models.TextField(blank=True, verbose_name='Motif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_approuves', to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='rh.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Congé',
                'verbose_name_plural': 'Congés',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ObjectifVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='Année')),
                ('mois', models.PositiveSmallIntegerField(verbose_name='Mois')),
                ('montant_objectif', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Montant objectif (GNF)')),
                ('montant_realise', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Montant réalisé (GNF)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs_vente', to='companies.company', verbose_name='Entreprise')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectifs_crees', to=settings.AUTH_USER_MODEL)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs_vente', to='companies.depot', verbose_name='Dépôt')),
            ],
            options={
                'verbose_name': 'Objectif de vente',
                'verbose_name_plural': 'Objectifs de vente',
                'ordering': ['-annee', '-mois'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('type_presence', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'Retard'), ('mission', 'En mission')], max_length=20, verbose_name='Type')),
                ('heure_arrivee', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('heure_depart', models.TimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='rh.employe', verbose_name='Employé')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_enregistrees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='employe',
            constraint=models.UniqueConstraint(fields=('company', 'matricule'), name='unique_matricule_par_company'),
        ),
        migrations.AddConstraint(
            model_name='objectifvente',
            constraint=models.UniqueConstraint(fields=('depot', 'annee', 'mois'), name='unique_objectif_depot_mois'),
        ),
        migrations.AddConstraint(
            model_name='presence',
            constraint=models.UniqueConstraint(fields=('employe', 'date'), name='unique_presence_employe_date'),
        ),
    ]
