# Generated by Django 5.2.14 on 2026-06-07 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_gestionnaire_depot'),
        ('logistique', '0004_mission_qr_code_vehicule_annee_and_more'),
        ('rh', '0001_initial'),
        ('stocks', '0001_initial'),
        ('ventes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='ventes.commande', verbose_name='Commande liée'),
        ),
        migrations.AddField(
            model_name='document',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='logistique.mission', verbose_name='Mission liée'),
        ),
        migrations.AddField(
            model_name='document',
            name='transfert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='stocks.transfertstock', verbose_name='Transfert lié'),
        ),
        migrations.CreateModel(
            name='HistoriqueAffectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(blank=True, verbose_name='Motif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depot_ancien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_depart', to='companies.depot', verbose_name='Ancien dépôt')),
                ('depot_nouveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_arrivee', to='companies.depot', verbose_name='Nouveau dépôt')),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_affectations', to='rh.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Historique affectation',
                'verbose_name_plural': 'Historiques affectations',
                'ordering': ['-created_at'],
            },
        ),
    ]
