# Generated by Django 5.2.14 on 2026-06-06 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_zone_latitude_zone_longitude'),
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Quantité')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='companies.depot', verbose_name='Dépôt')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='produits.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Stock dépôt',
                'verbose_name_plural': 'Stocks dépôts',
            },
        ),
        migrations.CreateModel(
            name='LotStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(blank=True, max_length=100, verbose_name='Numéro de lot')),
                ('quantite', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Quantité')),
                ('date_fabrication', models.DateField(blank=True, null=True, verbose_name='Date de fabrication')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='stocks.stockdepot', verbose_name='Stock dépôt')),
            ],
            options={
                'verbose_name': 'Lot de stock',
                'verbose_name_plural': 'Lots de stock',
                'ordering': ['date_expiration', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransfertStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Numéro')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_transit', 'En transit'), ('recu', 'Reçu'), ('annule', 'Annulé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('date_reception', models.DateTimeField(blank=True, null=True, verbose_name='Date de réception')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_stock', to='companies.company', verbose_name='Entreprise')),
                ('depot_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_arrivee', to='companies.depot', verbose_name='Dépôt destination')),
                ('depot_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_depart', to='companies.depot', verbose_name='Dépôt source')),
                ('utilisateur_envoi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='Envoyé par')),
                ('utilisateur_reception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_recus', to=settings.AUTH_USER_MODEL, verbose_name='Reçu par')),
            ],
            options={
                'verbose_name': 'Transfert de stock',
                'verbose_name_plural': 'Transferts de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('transfert_depart', 'Transfert — départ'), ('transfert_arrivee', 'Transfert — arrivée'), ('inventaire', 'Inventaire'), ('ajustement', 'Ajustement')], max_length=30, verbose_name='Type')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('quantite_avant', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité avant')),
                ('quantite_apres', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité après')),
                ('reference_doc', models.CharField(blank=True, help_text='N° de commande, BL, transfert, etc.', max_length=100, verbose_name='Référence document')),
                ('motif', models.TextField(blank=True, verbose_name='Motif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to='companies.depot', verbose_name='Dépôt')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='produits.produit', verbose_name='Produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('transfert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='stocks.transfertstock', verbose_name='Transfert lié')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_envoyee', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Qté envoyée')),
                ('quantite_recue', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Qté reçue')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_transfert', to='produits.produit', verbose_name='Produit')),
                ('transfert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stocks.transfertstock', verbose_name='Transfert')),
            ],
            options={
                'verbose_name': 'Ligne de transfert',
                'verbose_name_plural': 'Lignes de transfert',
            },
        ),
        migrations.AddConstraint(
            model_name='stockdepot',
            constraint=models.UniqueConstraint(fields=('depot', 'produit'), name='unique_stock_depot_produit'),
        ),
        migrations.AddConstraint(
            model_name='lignetransfert',
            constraint=models.UniqueConstraint(fields=('transfert', 'produit'), name='unique_ligne_transfert_produit'),
        ),
    ]
