# Generated by Django 5.2.14 on 2026-06-07 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_gestionnaire_depot'),
        ('produits', '0002_categorie_tva_taux_commandefournisseur_and_more'),
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='fournisseur',
            field=models.ForeignKey(blank=True, help_text='Renseigné lors des entrées liées à une livraison fournisseur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='produits.fournisseur', verbose_name='Fournisseur'),
        ),
        migrations.CreateModel(
            name='AjustementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, help_text='Positif = ajout de stock, négatif = retrait', max_digits=12, verbose_name='Quantité')),
                ('motif', models.TextField(verbose_name='Motif')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('traite_le', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustements_stock', to='companies.company', verbose_name='Entreprise')),
                ('demande_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustements_demandes', to=settings.AUTH_USER_MODEL, verbose_name='Demandé par')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustements_stock', to='companies.depot', verbose_name='Dépôt')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustements_stock', to='produits.produit', verbose_name='Produit')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustements_traites', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': 'Ajustement de stock',
                'verbose_name_plural': 'Ajustements de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('annule', 'Annulé')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Numéro')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valide_le', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='companies.company', verbose_name='Entreprise')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventaires_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventaires', to='companies.depot', verbose_name='Dépôt')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_theorique', models.DecimalField(decimal_places=3, help_text="Lue depuis StockDepot au moment de la création de l'inventaire", max_digits=12, verbose_name='Quantité théorique')),
                ('quantite_comptee', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Quantité comptée')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stocks.inventaire', verbose_name='Inventaire')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_inventaire', to='produits.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': "Ligne d'inventaire",
                'verbose_name_plural': "Lignes d'inventaire",
                'constraints': [models.UniqueConstraint(fields=('inventaire', 'produit'), name='unique_ligne_inventaire_produit')],
            },
        ),
    ]
