# Generated by Django 5.2.15 on 2026-06-18 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_zone_code_unique_per_company_depot_code_unique_per_zone'),
        ('stocks', '0002_mouvementstock_fournisseur_ajustementstock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='numero',
            field=models.CharField(max_length=30, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='transfertstock',
            name='numero',
            field=models.CharField(max_length=30, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='transfertstock',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', "Validé — en attente d'expédition"), ('en_transit', 'En transit'), ('recu', 'Reçu'), ('annule', 'Annulé')], default='brouillon', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddConstraint(
            model_name='inventaire',
            constraint=models.UniqueConstraint(fields=('company', 'numero'), name='unique_inventaire_numero_per_company'),
        ),
        migrations.AddConstraint(
            model_name='transfertstock',
            constraint=models.UniqueConstraint(fields=('company', 'numero'), name='unique_transfert_stock_numero_per_company'),
        ),
    ]
