# Generated by Django 5.2.14 on 2026-06-07 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_gestionnaire_depot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('rupture_stock', 'Rupture de stock'), ('seuil_stock', 'Seuil de stock atteint'), ('ecart_caisse', 'Écart de caisse'), ('mission_litige', 'Mission en litige'), ('taux_change_expire', 'Taux de change expiré'), ('echeance_client', 'Échéance client'), ('transfert_valide', 'Transfert de stock reçu'), ('conge_approuve', 'Congé approuvé'), ('maintenance_vehicule', 'Maintenance véhicule'), ('commande_fournisseur', 'Commande fournisseur'), ('info', 'Information')], default='info', max_length=30, verbose_name='Type')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('lien', models.CharField(blank=True, help_text='URL relative vers la ressource concernée', max_length=300, verbose_name='Lien')),
                ('est_lue', models.BooleanField(default=False, verbose_name='Lue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='companies.company', verbose_name='Entreprise')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
